# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purlieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('north', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Norte (*)')),
                ('south', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sur (*)')),
                ('east', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Este (*)')),
                ('west', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Este (*)')),
                ('land_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Area del terreno (*)')),
                ('covered_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Area cubierta (*)')),
                ('built_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Area construida (*)')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Area total (*)')),
            ],
            options={
                'verbose_name_plural': 'Linderos',
                'verbose_name': 'Lindero',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre de la especie', max_length=100, verbose_name='Nombre (*)')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Especies',
                'verbose_name': 'Especie',
            },
        ),
    ]
