# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_semoviente_breed'),
        ('parameters', '0002_purlieu_species'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Breed',
        ),
        migrations.AddField(
            model_name='species',
            name='specie_suc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parameters.Species', verbose_name='Especie (*)'),
        ),
        migrations.AlterField(
            model_name='model',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.Make', verbose_name='Marca (*)'),
        ),
    ]
