# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20160506_0111'),
        ('parameters', '0002_purlieu_species'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purlieu',
        ),
    ]
