# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0003_auto_20160506_0023'),
        ('parameters', '0003_delete_purlieu'),
    ]

    operations = [
    ]
