# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_administrativeunit_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeunit',
            name='entity',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='entities.Entity', verbose_name='Entidad'),
        ),
    ]
