# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 06:11
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_administrativeunit_entity'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='entity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.Entity'),
        ),
    ]
