# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 05:41
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purlieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('north', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Norte (*)')),
                ('south', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sur (*)')),
                ('east', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Este (*)')),
                ('west', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Este (*)')),
                ('land_area', models.DecimalField(
                    decimal_places=2, max_digits=10, verbose_name='Area del terreno (*)')),
                ('covered_area', models.DecimalField(
                    decimal_places=2, max_digits=10, verbose_name='Area cubierta (*)')),
                ('built_area', models.DecimalField(
                    decimal_places=2, max_digits=10, verbose_name='Area construida (*)')),
                ('total_area', models.DecimalField(
                    decimal_places=2, max_digits=10, verbose_name='Area total (*)')),
            ],
            options={
                'verbose_name_plural': 'Linderos',
                'verbose_name': 'Lindero',
            },
        ),
        migrations.AlterModelOptions(
            name='furnishing',
            options={'verbose_name': 'Mueble', 'verbose_name_plural': 'Muebles'},
        ),
        migrations.AlterField(
            model_name='assets',
            name='furnishing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Furnishing'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='property',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Property'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='semoviente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Semoviente'),
        ),
        migrations.AlterField(
            model_name='property',
            name='purlieu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goods.Purlieu'),
        ),
    ]
