# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_administrativeunit_entity'),
        ('goods', '0002_auto_20160506_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='administrative_unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='entities.AdministrativeUnit'),
            preserve_default=False,
        ),
    ]
