# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 05:58
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_catalog_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='code',
            field=models.CharField(
                blank=True, help_text='Ingrese el codigo del activo', max_length=100,
                verbose_name='Codigo alterno (*)'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='correlative',
            field=models.SlugField(
                editable=False, help_text='Ingrese el correlativo del activo', max_length=100,
                unique=True, verbose_name='Correlativo (*)'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='origin',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Catalog'),
        ),
    ]
