# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20160506_0254'),
        ('goods', '0002_remove_semoviente_breed'),
    ]

    operations = [
    ]
