# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semoviente',
            name='semoviente_suc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Semoviente'),
        ),
    ]
