# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20160506_0240'),
        ('goods', '0009_auto_20160506_0417'),
    ]

    operations = [
    ]
