# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 09:20
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semoviente',
            name='semoviente_suc',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Semoviente',
                verbose_name='Semoviente madre'),
        ),
    ]
