# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 00:59
from django.db import migrations


def ExportDataRegions(apps, schema_editor):
    from regions.models import Paises, Estados, Ciudades, Municipios, Parroquias
    import json
    with open("venezuela.json") as json_file:
        json_data = json.load(json_file)
        pais = Paises.objects.create(nombre="Venezuela")
        for estado in json_data:
            estado_obj = Estados.objects.create(
                pais=pais,
                nombre=estado["estado"]
            )
            for municipio in estado["municipios"]:
                ciudad_obj = Ciudades.objects.create(
                    estado=estado_obj,
                    nombre=municipio["capital"],
                )

                municipio_obj = Municipios.objects.create(
                    ciudad=ciudad_obj,
                    nombre=municipio["municipio"],
                )
                for parroquia in municipio["parroquias"]:
                    Parroquias.objects.create(
                        municipio=municipio_obj,
                        nombre=parroquia
                    )


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(ExportDataRegions),
    ]
