# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 00:48
from __future__ import unicode_literals

from django.db import migrations


def ExportDataRegions(apps, schema_editor):
    from regions.models import Country, Estate, City, Municipality, Parish
    import json
    with open("venezuela.json") as json_file:
        json_data = json.load(json_file)
        pais = Country.objects.create(name="Venezuela")
        for estado in json_data:
            estado_obj = Estate.objects.create(
                country=pais,
                name=estado["estado"]
            )
            for municipio in estado["municipios"]:
                ciudad_obj = City.objects.create(
                    estate=estado_obj,
                    name=municipio["capital"],
                )

                municipio_obj = Municipality.objects.create(
                    city=ciudad_obj,
                    name=municipio["municipio"],
                )
                for parroquia in municipio["parroquias"]:
                    Parish.objects.create(
                        municipality=municipio_obj,
                        name=parroquia
                    )


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(ExportDataRegions),
    ]
